id: ABF202A4A
title: 'Streams of Sapphire: A Prayer to the Eighty-Four Mahāsiddhas'
type: translation
pechas:
- I22A1548D
- I08333D8D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:39:09.948652
  last_modified_at: 2023-01-04 12:39:09.948672
  collections:
  - Jedrung Jampa Jungné Series
  - Works of Tibetan Masters
alignment_to_base:
  I22A1548D/C3A4: ECB9
  I08333D8D/E4F1: ECB9
